MIAUI draft
rachelkang/AuthenticationSamples pull request #16
Opened 2022-07-19 17:37 UTC by gal42

MIAUI sample draft for reference. Started to work on adding new task. Has bugs with InitializeComponent method

2022-07-19 19:08 UTC, officialgio commented
Try deleting the old code regarding MVVM and INotifyProperyChanged - try using CommunityToolkit.Mvvm Nuget Package.

2022-08-02 22:08 UTC, tj-devel709 commented on MIAUI/Views/NewTaskPage.xaml.cs
>  	public Model.Task Task;
Is this Task Variable is being used here?

2022-08-02 23:15 UTC, rachelkang requested changes
Awesome work so far! 

Let's just do a little bit of clean up before we merge this - delete all the code that isn't being used (usings, commented code, unused variables). Then, we should be good to move forward :)

2022-08-03 17:23 UTC, davidortinau reviewed
Looking good!

As time permits you should refactor colors and control styles into static resources. https://docs.microsoft.com/en-us/dotnet/maui/user-interface/styles/xaml

2022-08-03 17:23 UTC, davidortinau commented on MIAUI/ViewModels/BaseViewModel.cs
> +    public partial class BaseViewModel : ObservableObject
Nuke this file since you don't need it

2022-08-03 17:23 UTC, davidortinau commented on MIAUI/ViewModels/SubtasksViewModel.cs
> +    public partial class SubtasksViewModel : BaseViewModel
```suggestion
    [INotifyPropertyChanged]
    public partial class SubtasksViewModel
```

No longer need this

2022-08-03 17:23 UTC, davidortinau commented on MIAUI/ViewModels/TasksViewModel.cs
> +    public partial class TasksViewModel : BaseViewModel
```suggestion
    [INotifyPropertyChanged]
    public partial class TasksViewModel
```

2022-08-03 17:23 UTC, davidortinau commented on MIAUI/ViewModels/SubtasksViewModel.cs
> +﻿using CommunityToolkit.Mvvm.ComponentModel;
How about adding a `GlobalUsings.cs` file to the root and moving the common using statements there to clean up your other files. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#global-modifier

2022-08-03 17:23 UTC, davidortinau commented on MIAUI/ViewModels/TasksViewModel.cs
> +        [ICommand]
I happen to notice in the latest pre-release of the CommunityToolkit.Mvvm that ICommand is gone and everything seems to be RelayCommand. Probably no reason to adopt a pre-release, but just a heads up.

2022-08-03 20:48 UTC, merged