[MIAUI] Add README and organized code
rachelkang/AuthenticationSamples pull request #39
Opened 2022-08-16 17:52 UTC by gal42

Added readme and organized code into folders to match the ones in the dotnet/maui-samples repo for the MIAUI sample

2022-08-17 16:25 UTC, rachelkang requested changes
Awesome work getting this cleaned up! 

I've left some comments that will help to clean it up just a bit more :)

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/MIAUI/FileAccessHelper.cs
> +        return System.IO.Path.Combine (FileSystem.AppDataDirectory, filename);
Since this is only being used in one place, we can remove this file and method and move the code directly to where it's being used in MauiProgram.cs

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/MIAUI/GlobalUsings.cs
> +global using SQLite;
nitpick: let's keep this file alphabetized! Move line 8 to line 6

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/MIAUI/TasksRepository.cs
> +public class TasksRepository
I recommend moving this file into a new folder called "Data"

See https://github.com/xamarin/xamarin-forms-samples/tree/main/Todo/Todo/Todo as an example

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/MIAUI/ViewModels/ProfilePageViewModel.cs
> +{
Since this ViewModel is empty and not being used anywhere, we can delete this file!

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/MIAUI/Views/LoginPage.xaml.cs
> +	public LoginPage (LoginViewModel vm)
Let's avoid passing the LoginViewModel as a parameter and instantiate it within the constructor instead, as has already been done with the other pages

2022-08-17 16:25 UTC, rachelkang commented on MIAUI/README.md
> +
Awesome screenshots! Be sure to include them in the README here as well so that they can shine :)

2022-08-17 17:49 UTC, tj-devel709 commented on MIAUI/MIAUI/AppShell.xaml.cs
> +        //Routing.RegisterRoute (nameof(LoginPage), typeof (LoginPage));
```suggestion
```

2022-08-17 17:49 UTC, tj-devel709 commented on MIAUI/MIAUI/AppShell.xaml.cs
> +        Routing.RegisterRoute (nameof (DetailsPage), typeof (DetailsPage));
You can fix indentation here

2022-08-17 17:50 UTC, tj-devel709 commented on MIAUI/MIAUI/MauiProgram.cs
> +        string dbPath = FileAccessHelper.GetLocalFilePath ("Task.db3"); ;
```suggestion
        string dbPath = FileAccessHelper.GetLocalFilePath ("Task.db3");
```
Also indentation

2022-08-17 17:51 UTC, tj-devel709 commented on MIAUI/MIAUI/MauiProgram.cs
> +        builder.Services.AddSingleton<TasksRepository> (s => ActivatorUtilities.CreateInstance<TasksRepository> (s, dbPath));
Indentation here as well :)

2022-08-17 17:51 UTC, tj-devel709 commented on MIAUI/MIAUI/TasksRepository.cs
> +        if (conn != null)
```suggestion
        if (conn is not null)
```

2022-08-17 17:52 UTC, tj-devel709 commented on MIAUI/MIAUI/TasksRepository.cs
> +            result = conn.Insert (new Model.Task(taskName));
```suggestion
            result = conn.Insert (new Model.Task (taskName));
```

2022-08-17 17:52 UTC, tj-devel709 commented on MIAUI/MIAUI/TasksRepository.cs
> +            Console.WriteLine(string.Format("Failed to add {0}. Error: {1}", taskName, ex.Message));
```suggestion
            Console.WriteLine (string.Format ("Failed to add {0}. Error: {1}", taskName, ex.Message));
```

2022-08-17 17:53 UTC, tj-devel709 commented on MIAUI/MIAUI/TasksRepository.cs
> +        return result;
```suggestion
       return conn.Update (task);
```
I think this should work and is less code

2022-08-17 17:54 UTC, tj-devel709 commented on MIAUI/MIAUI/TasksRepository.cs
> +        return result;
```suggestion
        return conn.Delete<Model.Task> (id);
```
similarly

2022-08-17 17:55 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +        //Details = detailsInfo;
```suggestion
```

2022-08-17 17:55 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +        //add TaskName
```suggestion
```

2022-08-17 17:56 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +
nit
```suggestion
```

2022-08-17 18:00 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
>          //fetch from database and fill items
```suggestion
```

2022-08-17 18:01 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
>          if (string.IsNullOrWhiteSpace(TaskName))
```suggestion
        if (string.IsNullOrWhiteSpace (TaskName))
```

2022-08-17 18:01 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +        await Shell.Current.GoToAsync ($"{nameof(DetailsPage)}",
```suggestion
        await Shell.Current.GoToAsync ($"{nameof (DetailsPage)}",
```

2022-08-17 18:02 UTC, tj-devel709 commented on MIAUI/MIAUI/Views/DetailsPage.xaml.cs
> +}
Don't forget to add a new line here

2022-08-17 18:02 UTC, tj-devel709 commented on MIAUI/MIAUI/Views/LoginPage.xaml.cs
> +}
Missing new line here :)

2022-08-17 18:02 UTC, tj-devel709 commented on MIAUI/MIAUI/Views/ProfilePage.xaml.cs
>  }
New line

2022-08-17 18:04 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/LoginViewModel.cs
> +                await Shell.Current.GoToAsync ($"{nameof(TasksPage)}",
```suggestion
                await Shell.Current.GoToAsync ($"{nameof (TasksPage)}",
```

2022-08-17 18:05 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/LoginViewModel.cs
> +                    [nameof(User)] = user
```suggestion
                    [nameof (User)] = user
```

2022-08-17 18:07 UTC, tj-devel709 reviewed
Great clean up so far! Left a few more suggestions to clean things!

2022-08-18 20:47 UTC, tj-devel709 approved these changes

2022-08-18 20:57 UTC, rachelkang requested changes
I left [some comments](https://github.com/rachelkang/AuthenticationSamples/pull/40#pullrequestreview-1077983941) on your B2C PR, most of which also apply here! Be sure to check them out :)

2022-08-18 20:57 UTC, tj-devel709 reviewed
Left a few more comments here!

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/Data/TasksRepository.cs
> +            result = 0;
```suggestion
```
This line should be removed as it hides any errors

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +[QueryProperty(nameof (Task), "Task")]
```suggestion
[QueryProperty (nameof (Task), "Task")]
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +[QueryProperty(nameof (TaskName), "TaskName")]
```suggestion
[QueryProperty (nameof (TaskName), "TaskName")]
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/DetailsViewModel.cs
> +[QueryProperty(nameof (DetailsInfo), "Details")]
```suggestion
[QueryProperty (nameof (DetailsInfo), "Details")]
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```

2022-08-18 20:57 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +        await Shell.Current.GoToAsync ($"{nameof(DetailsPage)}",
bumping this one

2022-08-19 15:48 UTC, tj-devel709 commented on MIAUI/MIAUI/Service/Constants.cs
> +    public static readonly string ClientId = "ClientId"; // from App Registrations
This should be edited based on Rachel's comment in B2C

2022-08-19 15:50 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +    //This delete method needs to interact with the database
```suggestion
```

2022-08-19 15:51 UTC, tj-devel709 commented on MIAUI/MIAUI/Views/LoginPage.xaml.cs
> +		BindingContext = new LoginViewModel();
```suggestion
		BindingContext = new LoginViewModel ();
```

2022-08-19 20:39 UTC, tj-devel709 commented on MIAUI/MIAUI/ViewModels/TasksViewModel.cs
> +
```suggestion
```
Keep the attribute with the method

2022-08-19 20:40 UTC, merged